// Generated by gencpp from file arm_gazebo/fkRequest.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_FKREQUEST_H
#define ARM_GAZEBO_MESSAGE_FKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct fkRequest_
{
  typedef fkRequest_<ContainerAllocator> Type;

  fkRequest_()
    : jointAngles()
    , linkAengths()  {
    }
  fkRequest_(const ContainerAllocator& _alloc)
    : jointAngles(_alloc)
    , linkAengths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _jointAngles_type;
  _jointAngles_type jointAngles;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _linkAengths_type;
  _linkAengths_type linkAengths;





  typedef boost::shared_ptr< ::arm_gazebo::fkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::fkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct fkRequest_

typedef ::arm_gazebo::fkRequest_<std::allocator<void> > fkRequest;

typedef boost::shared_ptr< ::arm_gazebo::fkRequest > fkRequestPtr;
typedef boost::shared_ptr< ::arm_gazebo::fkRequest const> fkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::fkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::fkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::fkRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::fkRequest_<ContainerAllocator2> & rhs)
{
  return lhs.jointAngles == rhs.jointAngles &&
    lhs.linkAengths == rhs.linkAengths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::fkRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::fkRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::fkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::fkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::fkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::fkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::fkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::fkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::fkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43298ecb5966ba4619f2e2482688a400";
  }

  static const char* value(const ::arm_gazebo::fkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43298ecb5966ba46ULL;
  static const uint64_t static_value2 = 0x19f2e2482688a400ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::fkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/fkRequest";
  }

  static const char* value(const ::arm_gazebo::fkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::fkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64[] jointAngles\n"
"float64[] linkAengths\n"
;
  }

  static const char* value(const ::arm_gazebo::fkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::fkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointAngles);
      stream.next(m.linkAengths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::fkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::fkRequest_<ContainerAllocator>& v)
  {
    s << indent << "jointAngles[]" << std::endl;
    for (size_t i = 0; i < v.jointAngles.size(); ++i)
    {
      s << indent << "  jointAngles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jointAngles[i]);
    }
    s << indent << "linkAengths[]" << std::endl;
    for (size_t i = 0; i < v.linkAengths.size(); ++i)
    {
      s << indent << "  linkAengths[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.linkAengths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_FKREQUEST_H
