(cl:in-package arm_lib-msg)
(cl:export '(FIRSTNAME-VAL
          FIRSTNAME
          LASTNAME-VAL
          LASTNAME
          COUNT-VAL
          COUNT
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ALPHA-VAL
          ALPHA
          BETA-VAL
          BETA
          GAMMA-VAL
          GAMMA
          NEWXX-VAL
          NEWXX
          NEWXY-VAL
          NEWXY
          NEWXZ-VAL
          NEWXZ
          NEWYX-VAL
          NEWYX
          NEWYY-VAL
          NEWYY
          NEWYZ-VAL
          NEWYZ
          NEWZX-VAL
          NEWZX
          NEWZY-VAL
          NEWZY
          NEWZZ-VAL
          NEWZZ
          DISTANCE-VAL
          DISTANCE
          FINALVECTORX1-VAL
          FINALVECTORX1
          FINALVECTORX2-VAL
          FINALVECTORX2
          FINALVECTORX3-VAL
          FINALVECTORX3
          FINALVECTORY1-VAL
          FINALVECTORY1
          FINALVECTORY2-VAL
          FINALVECTORY2
          FINALVECTORY3-VAL
          FINALVECTORY3
          FINALVECTORZ1-VAL
          FINALVECTORZ1
          FINALVECTORZ2-VAL
          FINALVECTORZ2
          FINALVECTORZ3-VAL
          FINALVECTORZ3
))